### ISSUE TITLE
An inquiry for the benchmark datasets

### ISSUE THREAD

**Issue by zhimin-z** [zyayoung/Awesome-Video-LLMs#1]
Does this work cover an official **benchmark** for video comprehension? I initially thought _VLM-Eval_ is a benchmark for video comprehension but it seems not.

**Comment by zyayoung** [comment]
Thanks for your correction. Currently, we do not provide an official benchmark, but this repo has all the evaluation codes, and you can build a benchmark based on these tasks.

**Comment by zhimin-z** [comment]
> Thanks for your correction. Currently, we do not provide an official benchmark, but this repo has all the evaluation codes, and you can build a benchmark based on these tasks.

May I ask what datasets are being used exactly for the evaluation? All of them below?
![image](https://github.com/zyayoung/Awesome-Video-LLMs/assets/8592144/65febc6f-def3-47c2-994a-47927d61d3cf)

**Comment by zyayoung** [comment]
The detailed evaluation dataset for each task is presented in the paper.
<img width="595" alt="image" src="https://github.com/zyayoung/Awesome-Video-LLMs/assets/6887683/994bab31-a709-45ed-92e8-f1ddbb5744c3">
Thanks for pointing out the ambiguity in this readme file. We will clarify it and present the detailed results on each dataset in the next repo update.
